# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

km <- function(e, d, p) {
    .Call(`_semirkosmac_km`, e, d, p)
}

gehan_ns <- function(x, y, d, beta, p, n) {
    .Call(`_semirkosmac_gehan_ns`, x, y, d, beta, p, n)
}

gehan_mtg <- function(x, d, e, ind) {
    .Call(`_semirkosmac_gehan_mtg`, x, d, e, ind)
}

gehan_smth <- function(x, y, d, p, b, n) {
    .Call(`_semirkosmac_gehan_smth`, x, y, d, p, b, n)
}

gehan_s_mtg <- function(x, y, d, p, bt, ind, n) {
    .Call(`_semirkosmac_gehan_s_mtg`, x, y, d, p, bt, ind, n)
}

gehan_s_jaco <- function(x, y, d, p, b, n) {
    .Call(`_semirkosmac_gehan_s_jaco`, x, y, d, p, b, n)
}

